// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlatformWindowsSeriallizer.proto

#include "PlatformWindowsSeriallizer.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_PlatformWindowsSeriallizer_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_WinResources_ResEntry_DoNotUse_PlatformWindowsSeriallizer_2eproto;
namespace PlatformWindowsSeriallizer {
class WinResources_ResEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<WinResources_ResEntry_DoNotUse> _instance;
} _WinResources_ResEntry_DoNotUse_default_instance_;
class WinResourcesDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<WinResources> _instance;
} _WinResources_default_instance_;
}  // namespace PlatformWindowsSeriallizer
static void InitDefaultsscc_info_WinResources_PlatformWindowsSeriallizer_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::PlatformWindowsSeriallizer::_WinResources_default_instance_;
    new (ptr) ::PlatformWindowsSeriallizer::WinResources();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PlatformWindowsSeriallizer::WinResources::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_WinResources_PlatformWindowsSeriallizer_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_WinResources_PlatformWindowsSeriallizer_2eproto}, {
      &scc_info_WinResources_ResEntry_DoNotUse_PlatformWindowsSeriallizer_2eproto.base,}};

static void InitDefaultsscc_info_WinResources_ResEntry_DoNotUse_PlatformWindowsSeriallizer_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::PlatformWindowsSeriallizer::_WinResources_ResEntry_DoNotUse_default_instance_;
    new (ptr) ::PlatformWindowsSeriallizer::WinResources_ResEntry_DoNotUse();
  }
  ::PlatformWindowsSeriallizer::WinResources_ResEntry_DoNotUse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_WinResources_ResEntry_DoNotUse_PlatformWindowsSeriallizer_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_WinResources_ResEntry_DoNotUse_PlatformWindowsSeriallizer_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_PlatformWindowsSeriallizer_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_PlatformWindowsSeriallizer_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_PlatformWindowsSeriallizer_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_PlatformWindowsSeriallizer_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::PlatformWindowsSeriallizer::WinResources_ResEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::PlatformWindowsSeriallizer::WinResources_ResEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::PlatformWindowsSeriallizer::WinResources_ResEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::PlatformWindowsSeriallizer::WinResources_ResEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PlatformWindowsSeriallizer::WinResources, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::PlatformWindowsSeriallizer::WinResources, res_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::PlatformWindowsSeriallizer::WinResources_ResEntry_DoNotUse)},
  { 9, -1, sizeof(::PlatformWindowsSeriallizer::WinResources)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::PlatformWindowsSeriallizer::_WinResources_ResEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::PlatformWindowsSeriallizer::_WinResources_default_instance_),
};

const char descriptor_table_protodef_PlatformWindowsSeriallizer_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n PlatformWindowsSeriallizer.proto\022\032Plat"
  "formWindowsSeriallizer\"z\n\014WinResources\022>"
  "\n\003res\030\001 \003(\01321.PlatformWindowsSeriallizer"
  ".WinResources.ResEntry\032*\n\010ResEntry\022\013\n\003ke"
  "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_PlatformWindowsSeriallizer_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_PlatformWindowsSeriallizer_2eproto_sccs[2] = {
  &scc_info_WinResources_PlatformWindowsSeriallizer_2eproto.base,
  &scc_info_WinResources_ResEntry_DoNotUse_PlatformWindowsSeriallizer_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_PlatformWindowsSeriallizer_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PlatformWindowsSeriallizer_2eproto = {
  false, false, descriptor_table_protodef_PlatformWindowsSeriallizer_2eproto, "PlatformWindowsSeriallizer.proto", 194,
  &descriptor_table_PlatformWindowsSeriallizer_2eproto_once, descriptor_table_PlatformWindowsSeriallizer_2eproto_sccs, descriptor_table_PlatformWindowsSeriallizer_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_PlatformWindowsSeriallizer_2eproto::offsets,
  file_level_metadata_PlatformWindowsSeriallizer_2eproto, 2, file_level_enum_descriptors_PlatformWindowsSeriallizer_2eproto, file_level_service_descriptors_PlatformWindowsSeriallizer_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_PlatformWindowsSeriallizer_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_PlatformWindowsSeriallizer_2eproto)), true);
namespace PlatformWindowsSeriallizer {

// ===================================================================

WinResources_ResEntry_DoNotUse::WinResources_ResEntry_DoNotUse() {}
WinResources_ResEntry_DoNotUse::WinResources_ResEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void WinResources_ResEntry_DoNotUse::MergeFrom(const WinResources_ResEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata WinResources_ResEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void WinResources_ResEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

void WinResources::InitAsDefaultInstance() {
}
class WinResources::_Internal {
 public:
};

WinResources::WinResources(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  res_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:PlatformWindowsSeriallizer.WinResources)
}
WinResources::WinResources(const WinResources& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  res_.MergeFrom(from.res_);
  // @@protoc_insertion_point(copy_constructor:PlatformWindowsSeriallizer.WinResources)
}

void WinResources::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_WinResources_PlatformWindowsSeriallizer_2eproto.base);
}

WinResources::~WinResources() {
  // @@protoc_insertion_point(destructor:PlatformWindowsSeriallizer.WinResources)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void WinResources::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void WinResources::ArenaDtor(void* object) {
  WinResources* _this = reinterpret_cast< WinResources* >(object);
  (void)_this;
}
void WinResources::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void WinResources::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const WinResources& WinResources::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_WinResources_PlatformWindowsSeriallizer_2eproto.base);
  return *internal_default_instance();
}


void WinResources::Clear() {
// @@protoc_insertion_point(message_clear_start:PlatformWindowsSeriallizer.WinResources)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  res_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WinResources::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // map<string, bytes> res = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&res_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* WinResources::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PlatformWindowsSeriallizer.WinResources)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, bytes> res = 1;
  if (!this->_internal_res().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "PlatformWindowsSeriallizer.WinResources.ResEntry.key");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_res().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_res().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_res().begin();
          it != this->_internal_res().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = WinResources_ResEntry_DoNotUse::Funcs::InternalSerialize(1, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_res().begin();
          it != this->_internal_res().end(); ++it) {
        target = WinResources_ResEntry_DoNotUse::Funcs::InternalSerialize(1, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PlatformWindowsSeriallizer.WinResources)
  return target;
}

size_t WinResources::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PlatformWindowsSeriallizer.WinResources)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, bytes> res = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_res_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_res().begin();
      it != this->_internal_res().end(); ++it) {
    total_size += WinResources_ResEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WinResources::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PlatformWindowsSeriallizer.WinResources)
  GOOGLE_DCHECK_NE(&from, this);
  const WinResources* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<WinResources>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PlatformWindowsSeriallizer.WinResources)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PlatformWindowsSeriallizer.WinResources)
    MergeFrom(*source);
  }
}

void WinResources::MergeFrom(const WinResources& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PlatformWindowsSeriallizer.WinResources)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  res_.MergeFrom(from.res_);
}

void WinResources::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PlatformWindowsSeriallizer.WinResources)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WinResources::CopyFrom(const WinResources& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PlatformWindowsSeriallizer.WinResources)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WinResources::IsInitialized() const {
  return true;
}

void WinResources::InternalSwap(WinResources* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  res_.Swap(&other->res_);
}

::PROTOBUF_NAMESPACE_ID::Metadata WinResources::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace PlatformWindowsSeriallizer
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PlatformWindowsSeriallizer::WinResources_ResEntry_DoNotUse* Arena::CreateMaybeMessage< ::PlatformWindowsSeriallizer::WinResources_ResEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PlatformWindowsSeriallizer::WinResources_ResEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::PlatformWindowsSeriallizer::WinResources* Arena::CreateMaybeMessage< ::PlatformWindowsSeriallizer::WinResources >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PlatformWindowsSeriallizer::WinResources >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
